version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hotelston-task
        ports:
            - '3000:3000'
        working_dir: /src/
        command: npm start
